### ISSUE TITLE
VBET Cartography Improvements

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/sqlBRAT#20]
Please implement the following improvements to the curated VBET web map.

1. Add a new base map that is simply a topographic hillshade using grey scale.
1. Make the aforementioned hill shade the default base map (keep the satellite imagery and topo base maps as options).
1. Change the symbology of the VBET valley bottoms as:
    1. solid green outline.
    1. Semi transparent green fill. (The idea is that if you turn on all the proability polygons then the overlapping transparencies will combine to provide more solid blocking for higher probability).

**Comment by MattReimer** [comment]
the base map as a hillshade is tricky because, right now anyway, I don't have a raster tileset for the whole country.

We can fake it with vector tiles from mapbox
https://studio.mapbox.com/styles/raychaser/ck80etogs05yl1inb7etenuq7/edit/#10.02/36.0009/-111.9055

But I'm not sure this is going to cut it.

**Comment by MattReimer** [comment]
Improvements have been made:
https://riverscapes.github.io/rs_maps/#/VBET
