### ISSUE TITLE
Review BRAT Run FIS

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/sqlBRAT#41]
The FIS processes in BRAT Run take a surprisingly long time when there are 20,000 or so reaches in a watershed.

Pleasae review both the [vegetation FIS](https://github.com/Riverscapes/sqlBRAT/blob/master/vegetation_fis.py) and [combined FIS](https://github.com/Riverscapes/sqlBRAT/blob/master/combined_fis.py) code for any easy performance gains. These two routines are virtually identical in structure.

**Comment by MattReimer** [comment]
So here's what we've got. There are two main loops that affect the FIS in BRAT Run:
* [Vegetation FIS Loop](https://github.com/Riverscapes/sqlBRAT/blob/master/vegetation_fis.py#L145-L161)
* [Combined FIS Loop](https://github.com/Riverscapes/sqlBRAT/blob/master/combined_fis.py#L219-L247)

### Vegetation FIS Loop

```
AVG_TIMER::FIS Timer:: Count: 21,100, Total Time: 193.814772s, Average: 9.185534ms     
```

so, each tick in the loop takes 9ms. 

### Combined FIS Loop

```
AVG_TIMER::FIS Timer:: Count: 18,540, Total Time: 303.236078s, Average: 16.355775ms     
```

This one is a lot slower with each tick taking an average of 16ms

---------------
In both of these cases the single limiting step is the `.compute()` step.

As of now there really isn't any way to speed this up unless we change our methodology to somehow run less of these computations.

We could look at implementing a key-value lookup table to make sure any combination of the same inputs gets looked up instead of computed but I'm not sure what benefit this would actually provide.

**Comment by MattReimer** [comment]
As of this investigation there really isn't much we can do to speed the FIS step up so I'm closing this.

**Comment by MattReimer** [comment]
Just for completeness I should mention that parralellization could speed this up too but that would entail augmenting our tool to be able to handle threads.
