### ISSUE TITLE
BRAT iGeo_Validation 

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/sqlBRAT#44]
**Passed:** 
iGeo_ElMax 
iGeo_ElMin
IsPeren

**Failed:**
iGeo_Slope
TotDASqKm
iPC_Road
iPC_RoadX
iPC_RoadVB
iPC_Rail
iPC_RailVB
iPC_DivPts
iPC_Canal
Agency --> all entries for sqlBRAT are blank

 
[Google Sheet] https://docs.google.com/spreadsheets/d/1NerNqb4U6uffCRo7g8uljmrqGKKgrWq9xpFj44QLEyc/edit?usp=sharing

[BRAT iGeo Validation.xlsx](https://github.com/Riverscapes/RaveAddIn/files/4664031/BRAT.iGeo.Validation.xlsx)

**Comment by philipbaileynar** [comment]
Closing this issue.

`Agency` is now fixed (so it `iPC_Privat` which was also accidentally getting set to NULL).

Yes, some of the values are quite different from pyBRAT, but they are in the right order of magnitude. 

Several other calibration tasks have been completed since this task was performed, and now sqlBRAT is producing much more comparable results with pyBRAT.

We will keep the spreadsheet for future reference.
