### ISSUE TITLE
Certain Rasters and Shapfiles are being cut off in certain watersheds

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/sqlBRAT#60]
In HUC 14050002 and 14050003, Historic Vegetation Rasters and Management Networks get completely cut off. This breaks many other values down the line as well.

![image](https://user-images.githubusercontent.com/27084463/86300814-b18f4a80-bbc9-11ea-861b-eabad211a1e5.png)
![image](https://user-images.githubusercontent.com/27084463/86300821-b522d180-bbc9-11ea-81fd-75d2b3fb47aa.png)

**Comment by philipbaileynar** [comment]
@Cashe93 are we sure that the landfire bps raster you created entirely covers this watershed?

**Comment by Cashe93** [comment]
@philipbaileynar, I believe so. HUCs 14050001, 14050002, & 14050003 all fall within the new LandFire BPS raster. 
![image](https://user-images.githubusercontent.com/49880208/86407321-10100380-bc72-11ea-9bd0-c748ae7594b9.png)

**Comment by philipbaileynar** [comment]
I am now fairly certain that this cut-off was caused by BRAT being run with out-of-date historic vegetation raster. @MattReimer please ensure that going forward, BRAT runs use the latest BPS raster that includes the additional region that @Cashe93 appended.

I have downloaded the latest BPS raster from the CRB program National Project and it does include the extended region. So somewhere along the line this version of the raster is not being made available to the EC2 model runs.

**Comment by MattReimer** [comment]
It's done. Next run should show this

**Comment by philipbaileynar** [comment]
Not sure what happened. It was almost certainly an out of date historical raster. I can confirm that the entire extent is being covered now.

<img width="1097" alt="Screen Shot 2020-07-16 at 8 27 47 PM" src="https://user-images.githubusercontent.com/8645379/87745470-d1fefd80-c7a2-11ea-9bf9-76f03aaf53d9.png">
