### ISSUE TITLE
Add JANMINT2K Hydrologic Attribute

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/sqlBRAT#68]
Some Oregon watersheds require an attribute that contains the mean minimum January temperature. This should be calculated just like the JANMAXT2K attribute, just using minimum instead. For more details, look at table 11 [here](https://pubs.usgs.gov/sir/2005/5116/pdf/sir2005-5116.pdf)

**Comment by philipbaileynar** [comment]
@tyler1218hatch I am going to assign this back to you and ask you to obtain the JANMAX2K value and then enter it into git. 

I say git because we have not implemented the ability to enter watershed hydrological parameters into Google Sheets. So these values need to go directly into git using a pull request please. (Note that this is where the Google Sheet values end up as well at the end of the day.)

So the process is as follows. Note that this is true for any watershed hydrological parameter (not just JANMAX2K):

1. Go find or calculate the hydrological parameter value in question.
1. Create a new branch for this change. Perhaps call it `HydroParam_JANMAX2K`.
1. Check the [HydroParams.csv](https://github.com/Riverscapes/sqlBRAT/blob/master/database/data/HydroParams.csv) file to see if the desired parameter is defined. Append it if it is not. Please avoid adding the same parameter twice! Also, pay close attention to the units and conversion factors.
1. Append the parameter value into the (WatershedHydroParam.csv](https://github.com/Riverscapes/sqlBRAT/blob/master/database/data/intersect/WatershedHydroParams.csv). Avoid reentering the same value for the same watershed twice. If the parameter applies to multiple HUCs then simple repeat the parameter value as many times as needed, just changing the WatershedID.
1. Commit the changes and push the branch. Assign the pull request to me.

Give me a call if you have any questions.

**Comment by tyler1218hatch** [comment]
@philipbaileynar Just created the pull request, let me know what you think.

**Comment by philipbaileynar** [comment]
Looks fantastic @tyler1218hatch really appreciative of your ability to interpret and then execute these changes with very little supervision. Thank you.

As I mentioned in the pull request, I am waiting until a big batch clears through the automation tonight before I rebase the pull request. Thanks!
