### ISSUE TITLE
Historic vegetation suitability raster NoData value

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/sqlBRAT#76]
The historic vegetation suitability raster NoData value is showing up as -1. These values should be NoData and transparent when the raster is added to the map.

<img width="2157" alt="Screen Shot 2020-07-15 at 3 33 57 PM" src="https://user-images.githubusercontent.com/8645379/87606749-9ab02400-c6b0-11ea-8e46-ac02c6dd2826.png">

Note that the existing vegetation suitability raster is working OK:

<img width="2157" alt="Screen Shot 2020-07-15 at 3 34 40 PM" src="https://user-images.githubusercontent.com/8645379/87606792-b4516b80-c6b0-11ea-8f87-e43a0565522b.png">

**Comment by MattReimer** [comment]
The issue here is that existing raster comes in with datatype int16 and historic comes in with uint16. We normalize this but historic has the nodata value set to be the greatest possible integer so that range gets halved when we convert and the nodata value becomes out of range. Should be fixed now.

**Comment by philipbaileynar** [comment]
@MattReimer was the solution to change code or fix the raster in the National Project?

It would be nice if the rasters were all consistent data formats.
